Make clang-format run only in the pre-commit hook, not in pipelines
- Document the pre-commit hook as mandatory.
- Changes the pre-commit hook to automatically apply clang-format changes only to lines modified in that commmit.
- This avoids unnecessary mass-changes when clang-format changes version which affects its output ever so slightly.
- This in turn avoids the need for clang-format to run in the pipelines, which prevents the problems with clang-format
versions needing to line up exactly.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -2,7 +2,7 @@
 #
 #################################################################
 #                                                               #
-# Copyright (c) 2020-2024 YottaDB LLC and/or its subsidiaries.  #
+# Copyright (c) 2020-2025 YottaDB LLC and/or its subsidiaries.  #
 # All rights reserved.                                          #
 #                                                               #
 #       This source code contains the intellectual property     #
@@ -123,14 +123,14 @@ foreach file ($filelist)
 end
 
 # ---------------------------------------------------------------------------
-# 4) Runs clang-format on all files and make sure there were no differences.
+# 4) Runs clang-format on all changed lines and commit any differences.
 # ---------------------------------------------------------------------------
-# We require at least clang-format-15
-set CLANG_FORMAT="`tools/ci/find-llvm-tool.sh clang-format 15`"
-if ($status) then
-	echo "warning: missing a recent version of clang-format, not running format checks"
-	echo "note: this could happen either if clang-format is not installed or if it's not a recent enough version"
+if ( `where clang-format-diff` == "" ) then
+	echo "clang-format (including clang-format-diff) is required to commit" && exit 1
 else
+	# Run clang-format on any modified lines
+	git diff -U0 --no-color --cached HEAD | clang-format-diff -p1 -i -regex=".*\.(c|h)"
+	# Check if there are unstaged changes (as opposed to staged and uncommitted)
 	foreach file ($filelist)
 		if (! -e $file) then
 			continue
@@ -138,7 +138,6 @@ else
 		set extension = $file:e
 		set fixlist = ""
 		if ( "c" == "$extension" || "h" == "$extension" ) then
-			"$CLANG_FORMAT" -i "$file"
 			# Check if there are unstaged changes (as opposed to staged and uncommitted)
 			git diff-files --exit-code --name-only -- "$file" >/dev/null
 			if ($status) then
@@ -147,7 +146,7 @@ else
 			endif
 		endif
 		if ("" != "$fixlist") then
-			echo "note: automatically commiting clang-format changes for the following files:"
+			echo "note: automatically committing clang-format changes for the following files:"
 			echo "$fixlist"
 		endif
 	end
