[#617] Optimize MAX(COLUMN) usage where COLUMN is a primary key column
Background
----------
* See https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/616#note_436143289 for original user report
  where the following query to find the maximum value of a primary key column took hours to finish.

  ```sql
  select max(order1_id) from order1;
  ```

Issue
-----
* As described at https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/617, the generated M code is not
  optimal for the above query in that it examines all rows of the table to determine the maximum.

* Given the `order1_id` column is a primary key column of the `order1` table, there is no need to
  do that. All we need to do is to do a `$ORDER(...,-1) to find the last `order1_id` value and
  substitute that right away as the `max(order1_id)` value.

* The changes in this commit optimize queries like the above where `max` or `min` are done on
  primary key columns.

* A future commit will optimize queries where `max` or `min` are done on non-primary key columns.

* And another future commit will optimize queries where `max` or `min` are done on a composite key
  column (a table with more than one primary key column).

High level Changes
------------------
* The changes in this commit followed the todo list steps outlined at
  https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/617#note_2142141907.

* Basically, simple queries that use aggregate functions MAX or MIN on primary key columns
  and don't have a WHERE clause or GROUP BY clause or HAVING clause are candidates for this
  optimization.

Implementation
--------------
* A new function `tmpl_tablejoin_octo617_optimize()` helps emit the optimized M code in case
  it is possible.

  It disables the optimization in lots of cases. Details are described as comments in the function
  in various code paths.

  It also sets `pplan->is_octo617_optimized` (a new field in the `PhysicalPlan` structure) to
  TRUE in case the optimization was done. This helps the caller `tmpl_tablejoin()` decide
  whether to continue emitting non-optimized code or return.

  3 new enums were added to `enum EmitSourceForm` in `src/m_templates/template_helpers.h`. This helps
  with emitting the optimized M code in the new function by using mostly pre-existing code in
  `tmpl_emit_source()`. This also required an interface change to `tmpl_emit_source()` where the
  `parm2` parameter was now a `(void *)` pointer instead of an integer. This is used to pass the
  key (`SqlKey *`) for the new enum cases.

Misc notes
----------
* Pre-existing logic in `tmpl_tablejoin.ctemplate` to determine the type of a key column
  was moved to a new function `is_keycol_type_string()` as it was now needed in more than
  one place.

* The `FMT_PLAN_DEFINITION` macro in `src/octo.h` was bumped now that the same query would have a
  different M plan due to the new optimization.

Test
----
* A new `test_aggregate_functions/TAF06` bats subtest has been added to test the optimization.

diff --git a/tests/test_aggregate_functions.bats.in b/tests/test_aggregate_functions.bats.in
--- a/tests/test_aggregate_functions.bats.in
+++ b/tests/test_aggregate_functions.bats.in
@@ -1,6 +1,6 @@
 #################################################################
 #								#
-# Copyright (c) 2020-2023 YottaDB LLC and/or its subsidiaries.	#
+# Copyright (c) 2020-2024 YottaDB LLC and/or its subsidiaries.	#
 # All rights reserved.						#
 #								#
 #	This source code contains the intellectual property	#
@@ -20,7 +20,7 @@ setup() {
 }
 
 teardown() {
-  corecheck
+	corecheck
 }
 
 @test "TAF01 : OCTO455 : AVG/MIN/MAX/SUM on empty table should return the NULL value if GROUP BY clause is absent" {
@@ -46,5 +46,26 @@ teardown() {
 @test "TAF05 : OCTO579 : Test of various error scenarios with aggregate function usage in UPDATE and DELETE queries" {
 	load_fixture TAF05_errors.sql subtest novv
 	verify_output TAF05_errors output.txt
+}
+
+@test "TAF06 : OCTO617 : Test MAX(COL) and MIN(COL) is optimized in various cases and not in various other cases" {
+	echo "# Run crosscheck on TAF06.sql" >> output.txt
+	run_query_in_octo_and_postgres_and_crosscheck_multiple_queries names TAF06.sql
+	echo "# Remove Octo M plans (_ydboctoP*.*) from the crosscheck run as the _ydboctoP*.m file names can differ" >> output.txt
+	echo "# when run through the JDBC driver (that uses the extended query protocol and which the crosscheck" >> output.txt
+	echo "# can invoke randomly) due to the addition of a LIMIT keyword (see YDBOcto@48c0b208 for more details)" >> output.txt
+	echo "# This can cause issues with a deterministic reference file as that includes lines from this M plan." >> output.txt
+	rm _ydbocto*
+	echo "# Combine queries from TAF06.sql and TAF06_octo.sql into one query file TAF06all.sql" >> output.txt
+	cat @PROJECT_SOURCE_DIR@/tests/fixtures/TAF06.sql @PROJECT_SOURCE_DIR@/tests/fixtures/TAF06_octo.sql > TAF06all.sql
+	# Get gvn data for tables used in TAF06all.sql
+	yottadb -run %XCMD 'for i=1:1:10 set ^TAF06octod(i)=""'			# data for TAF06octod table
+	yottadb -run %XCMD 'for i=1:1:10 set ^TAF06octoe($char(96+i))=""'	# data for TAF06octoe table
+	echo "# Run queries in TAF06all.sql using octo (for deterministic M plan names) [load_fixture TAF06all.sql]" >> output.txt
+	# Some queries can issue errors (e.g. ERR_MISTYPED_FUNCTION error when MIN(BOOLEAN) is attempted) hence the "|| true" below
+	octo -p -f TAF06all.sql >> output.txt 2>&1 || true
+	echo '# Find out which queries had M plans with $ORDER for loops. Those are the non-optimized queries.' >> output.txt
+	grep -E " select|FOR|------|ORDER|DATA" $(ls -1 _ydbocto*.m | sort_LC_ALL_C) | grep -v GroupBy | sed 's/.*[;:] //;' >> output.txt
+	verify_output TAF06 output.txt
 }
 
