Enhance stop_rocto() test framework function to help debug rare test failures due to timeout
Background
----------
* The `make-tls-ubuntu` pipeline job failed at https://gitlab.com/YottaDB/DBMS/YDBOcto/-/jobs/5881439679
  in the `TF03` subtest due to a ctest timeout (1500 seconds) in one rare test run.

  **make-tls-ubuntu job**
  ```
  155/155 Test #139: test_framework ..........................***Timeout 1500.11 sec
  ```

* The `asan-rocky` pipeline job failed at https://gitlab.com/YottaDB/DBMS/YDBOcto/-/jobs/5898943312,
  in another rare test run, in the `TCV041` subtest. Again due to a ctest timeout.

  **asan-rocky job**
  ```
  153/153 Test #96: test_create_view1_3 .....................***Timeout 1500.08 sec
  ```

Issue
-----
* I looked at both the `TF03` and `TCV041` subtests.

  **tests/test_framework.bats.in**
  ```sh
     51 @test "TF03: : Verify that regex used to match NOT NULL constraint error message works fine" {
     52         load_fixture customers.sql
     53         load_fixture customers.zwr
     54         stop_rocto
     55         test_port=$(start_rocto 1344 -aw)
  ```

  **tests/test_create_view1_3.bats.in**
  ```sh
     57 @test "TCV041 : Views working with tables having column level and table level constraints" {
     58         stop_rocto
     59         test_port=$(start_rocto 1344 -aw)
  ```

* Both subtests have a `stop_rocto` and examination of the test output directory contents reveals that
  the `start_rocto` AFTER the `stop_rocto` line did not happen (as that logs a `ROCTO START` message to the
  file `env.log` and that file contained only 1 such line corresponding to the rocto process started BEFORE
  the `stop_rocto` call above.

* This made me conclude that the timeout happened inside the `stop_rocto` function.

* The `stop_rocto` function sends a MUPIP STOP to the listener rocto process and waits for it and any
  server rocto pids to terminate. I suspect that the mupip stop somehow got ignored in the listener
  rocto process and is the cause of the indefinite wait which ends up as a timeout.

Fix
---
* Since this failure is not reproducible locally and happens rarely only in the pipeline, I have added
  more information to the `stop_rocto` function to log more information as it waits for the rocto
  listener and/or server pids to terminate.

* Hoping that will confirm the above suspicion (that the mupip stop got ignored in the listener rocto
  process) if/when the next failure of this kind happens in the pipeline.

diff --git a/tests/test_helpers.bash.in b/tests/test_helpers.bash.in
--- a/tests/test_helpers.bash.in
+++ b/tests/test_helpers.bash.in
@@ -467,24 +467,36 @@ start_rocto() {
 
 wait_for_rocto_server_pids_to_die() {
 	listener_pid=$(cat rocto.pid)
+	echo " `date -Ins` : listener PID [$listener_pid]" >> wait_for_rocto_server_pids_to_die.out
 	# Wait for rocto servers (i.e. children of the listener) to die
 	# The grep is to filter out non-rocto processes that can start with ASAN
 	# With clang, we found that llvm-symbolizer starts as a child process of rocto and won't die on its own
 	ps --no-headers --ppid $listener_pid | grep rocto | awk '{print $1}' | while read server_pid; do
 		# Wait for rocto server process to actually die
+		echo " `date -Ins` : Waiting for server PID [$server_pid] to die" >> wait_for_rocto_server_pids_to_die.out
 		tail --pid=$server_pid -f /dev/null
 	done
+	echo " `date -Ins` : Server PIDs wait : DONE" >> wait_for_rocto_server_pids_to_die.out
 }
 
 stop_rocto() {
 	# Wait for rocto listener to die
 	if [[ -e rocto.pid ]]; then
 		listener_pid=$(cat rocto.pid)
+		echo "# Output of [ps -f -p $listener_pid] follows" >> wait_for_rocto_server_pids_to_die.out
+		# Note that it is possible in some cases the listener pid is not alive (some test might explicitly kill it etc.).
+		# Therefore, avoid a bats test failure from the ps command below by adding a "|| true" at the end.
+		ps -f -p $listener_pid >> wait_for_rocto_server_pids_to_die.out || true
+		echo "# Output of [ps -f --ppid $listener_pid] follows" >> wait_for_rocto_server_pids_to_die.out
+		# Add " || true" for same reason as previous "ps -f"
+		ps -f --ppid $listener_pid >> wait_for_rocto_server_pids_to_die.out || true
 		# Signal listener rocto process to die
 		$ydb_dist/mupip stop $listener_pid
 		wait_for_rocto_server_pids_to_die
 		# Wait for listener rocto process to actually die
+		echo " `date -Ins` : Waiting for listener PID [$listener_pid] to die" >> wait_for_rocto_server_pids_to_die.out
 		tail --pid=$listener_pid -f /dev/null
+		echo " `date -Ins` : Listener PID wait : DONE" >> wait_for_rocto_server_pids_to_die.out
 		# Release port number held by rocto (stored in the file "rocto.port")
 		local lockfile=@TEST_OUTPUT_DIR@/find_open_port
 		local test_port=`cat rocto.port`
