[#803] [fuzzing] Fix SIG-11/assert-fail if CREATE TABLE or SELECT query uses more than 256 key columns
Background
----------
* Below is pasted from (2) in https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/803#note_1492162026

  **Assert failed get_key_columns.c:47**
  ```sql
  OCTO> create table tmp (id integer key num 1000);
  octo: src/get_key_columns.c:47: get_key_columns: Assertion 'MAX_KEY_COUNT > key_num' failed.
  %YDB-F-KILLBYSIGSINFO1, YottaDB process 61105 has been killed by a signal 6 at address 0x00007F243B007A7C (vaddr 0x000000E40000EEB1)
  ```

* Below is a related issue pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/803#note_1494151801

  **SIG-11 in iterate_keys.c:472**

  While trying out test cases manually related to the test case in the previous bullet, I got the below failure
  symptom. This is a test case that tries to use a `SELECT query` involving more than 256 keys (whereas
  the previous bullet involves a `CREATE TABLE command` that has more than 256 keys).

  ```sql
  OCTO> drop table if exists c;
  DROP TABLE
  OCTO> create table c ( id0 INTEGER, id1 INTEGER, id2 INTEGER, id3 INTEGER, id4 INTEGER, id5 INTEGER, id6 INTEGER, id7 INTEGER, name VARCHAR(20), PRIMARY KEY (id0, id1, id2, id3, id4, id5, id6, id7));
  CREATE TABLE
  OCTO> select 1 from  c c1, c c2, c c3, c c4, c c5, c c6, c c7, c c8, c c9, c c10, c c11, c c12, c c13, c c14, c c15, c c16, c c17, c c18, c c19, c c20, c c21, c c22, c c23, c c24, c c25, c c26, c c27, c c28, c c29, c c30, c c31, c c32, c c33;
  %YDB-F-KILLBYSIGSINFO1, YottaDB process 25512 has been killed by a signal 11 at address 0x00005573C03FF6E9 (vaddr 0x00005579D232C1DC)
  %YDB-F-SIGMAPERR, Signal was caused by an address not mapped to an object
  ```

* Below is a related issue pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/803#note_1494165192

  A similar issue as the previous 2 bullets exists if one tries to create a table with 257 key columns using
  the `PRIMARY KEY` constraint keyword and specifying all the table columns in that list. Noting this here
  so we add an automated test for this use case as part of fixing the issues in the previous 2 bullets.

Issue
-----
* The macro `MAX_KEY_COUNT` is set to 255 in the Octo code base and is used everywhere to allocate memory
  with the assumption that any table/SELECT-query will never need more than those many keys.

* But this assumption is never enforced in the code. That means if one tries to execute a CREATE TABLE or
  SELECT command that needs more keys, one gets a SIG-11.

Fix
---
* The fix is to check at various points if the key count becomes more than `MAX_KEY_COUNT` and if so issue
  an error. That way we avoid proceeding further and causing the SIG-11.

* A new `ERR_TOO_MANY_TABLE_KEYCOLS` error is issued if a `CREATE TABLE` command uses more than 256 key columns.

* A new `ERR_TOO_MANY_SELECT_KEYCOLS` error is issued if a `SELECT` query uses enough tables in the JOIN list
  that cumulatively end up comprising more than 256 key columns.

* The checks are done in the following places respectively for each of the 3 issues/bullets in the `Background`
  section.
  - src/get_key_columns.c
  - src/physical/generate_physical_plan.c
  - src/parser/table_definition.c

* While at this, I noticed that `MAX_KEY_COUNT` is defined to be 255. I bumped this to be a round 256 instead.

Test
----
* The `test_fuzzing_queries/TFQ01` subtest has been enhanced to test all 3 bullets in the `Background` section.

diff --git a/tests/test_fuzzing_queries.bats.in b/tests/test_fuzzing_queries.bats.in
--- a/tests/test_fuzzing_queries.bats.in
+++ b/tests/test_fuzzing_queries.bats.in
@@ -23,5 +23,9 @@ teardown() {
 
 @test "TFQ01 : Test various queries generated by fuzz testing" {
 	load_fixture TFQ01.sql subtest novv
+	yottadb -run gen257keycols^TFQ01 > TFQ01a.sql
+	echo "-- This used to previously SIG-11." >> output.txt
+	echo "-- Expected output is an ERR_TOO_MANY_KEYCOLS error" >> output.txt
+	octo -f TFQ01a.sql &>> output.txt || true
 	verify_output TFQ01 output.txt noinfo nodebug
 }
