[#913] Fix old_input_line_begin maintenance (caused assert failure in readline_get_more.c during seed-reload)
Background
----------
* As part of https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1244#note_1375473876, I was trying out
  some experiments with `seedreload = "TRUE"` in `octo.conf`.

* When I ran the bats test suite, I noticed the `TPK01` subtest fail with a core file in that case.

  ```
  $ cat startinclude_vista-mini.out
  .
  .
  octo: src/readline_get_more.c:73: readline_get_more: Assertion `old_input_line_begin >= input_buffer_combined' failed.
  .
  .
  ```

Issue
-----
* It turns out to be a regression that was introduced by 046a3194.

* That commit introduced a global variable `old_input_line_begin` that is maintained in sync with
  another global variable `input_buffer_combined`.

* This commit did the keep-in-sync part in `src/readline_get_more.c`. But it forgot to do the same
  thing in the `COPY_QUERY_TO_INPUT_BUFFER` macro in `src/octo.h`. That is the issue which caused
  the two to go out of sync when an auto-upgrade (initiated by the `seedreload = "TRUE"` setting in
  octo.conf) recreated the tables based on a long table text definition (the norm in vista-mini.sql).

Fix
---
* As part of this commit, the keep-in-sync code in `src/readline_get_more.c` is now incorporated
  into the `COPY_QUERY_TO_INPUT_BUFFER` macro in `src/octo.h`.

* In addition, in `src/get_display_relation_query_stmt.c`, we save/restore the global variable
  `input_buffer_combined` and so we do the same with the global variable `old_input_line_begin`.

Test
----
* A new `test_createtable/TC077` subtest verifies this fix. Also verified that this test fails the
  assert without the code fixes in this commit.

diff --git a/tests/test_createtable.bats.in b/tests/test_createtable.bats.in
--- a/tests/test_createtable.bats.in
+++ b/tests/test_createtable.bats.in
@@ -923,3 +923,16 @@ OCTO
 	verify_output TC076_errors output.txt
 }
 
+@test "TC077 : OCTO913 : Test old_input_line_begin maintenance in readline_get_more.c (used to asert fail)" {
+	# Run only if build is of type "Debug", `seedreload` config is only available in "Debug" build
+	if [[ "Debug" != @CMAKE_BUILD_TYPE@ ]]; then
+		skip
+	fi
+	# This test used to previously assert fail in the second "load_fixture" call below as follows.
+	#	octo: src/readline_get_more.c:73: readline_get_more: Assertion `old_input_line_begin >= input_buffer_combined' failed.
+	#	%YDB-F-KILLBYSIGSINFO1, YottaDB process 93300 has been killed by a signal 6 at address 0x00007F5CC3C8BA7C (vaddr 0x000000E400016C74)
+	echo 'seedreload = "TRUE"' > octo.conf
+	load_fixture vista-mini.sql || true
+	load_fixture vista-mini.sql || true
+}
+
