[#617] Optimize MAX(COLUMN)/MIN(COLUMN) usage where COLUMN is NOT a primary key column
Background
----------
* Commit 025ab720 took care of optimizing `MAX(COLUMN)` and `MIN(COLUMN)` usages where
  `COLUMN` was a primary key column.

* This commit takes care of optimizing the same when `COLUMN` is NOT a primary key column.

Implementation
--------------
* For a `MAX(id)` reference in a select query in the `names` table, we can compute
  that value using `$ORDER(^names(""),-1)` and avoid scanning every row of the table.

* But for a `MAX(lastname)` reference in the same query, we can compute that value using
  `$ORDER(^%ydbAIMDERzGTIrQTVBoOhdanoKcC7(2,""),-1)`.

* 025ab720 had logic in `tmpl_tablejoin_octo617_optimize()` to do the following 2 bullets.
  - Check if the MAX/MIN optimization was possible
  - Emit optimized M code in case the optimization was possible.

* While this was okay to do in case of a primary key column, we need to do this at an earlier stage
  in case of a non-key column. This is because, we need to generate a cross reference plan for the
  `lastname` column (which will populate `^%ydbAIMDERzGTIrQTVBoOhdanoKcC7(2,*)`). And doing this
  has to be done BEFORE `tmpl_tablejoin_octo617_optimize`.

* Therefore, the logic in `tmpl_tablejoin_octo617_optimize` has been split so the first bullet
  which checked if the MAX/MIN optimization was possible is now moved to a new function
  `is_octo617_optimization_possible()` and is invoked by `generate_physical_plan.c` way before
  the template functions are invoked.

* The second bullet which emitted optimized M code continues to stay in `tmpl_tablejoin_octo617_optimize`.

* The new `is_octo617_optimization_possible()` function also notes down if the MAX/MIN aggregate
  function usage is on a key or non-key column. If a non-key column, it sets a new field
  `af->extra_detail.lp_aggregate_function.octo617_xref_plan` (in the `LogicalPlan` structure)
  to the xref plan by invoking `lp_generate_xref_plan()`.

* In `generate_physical_plan.c`, if we find that MAX/MIN optimization is possible after the
  `is_octo617_optimization_possible()` call, we go through all aggregate functions in the query
  and check if any usages need a corresponding xref plan (i.e. have a non-NULL `octo617_xref_plan`
  field) and if so invoke `generate_physical_plan()` on that xref plan thereby emitting M code
  to generate the xref plan.

* In `tmpl_tablejoin.ctemplate`, we previously used to invoke `tmpl_tablejoin_octo617_optimize()`
  unconditionally. But now we check if `pplan->is_octo617_optimized` is TRUE (i.e. the result of
  the first bullet) and only in that case we invoke this function (to finish the second bullet).

* These changes also resulted in simplifying the interface of `tmpl_tablejoin_octo617_optimize()`.

* And finally, `tmpl_tablejoin_octo617_optimize()` was reworked to emit the appropriate M code
  in case of not just a key column but also for a non-key column.

  Previously, `MIN` and `MAX` aggregate functions were optimized only for a primary key column and
  so they were guaranteed to never encounter a `NULL` value. But now that they can be optimized
  even for a non-key column which can take on `NULL` values, we need to ensure these functions
  never return the `NULL` value as long as there is at least one non-NULL value for this non-key
  column. This is taken care of by emitting M code which does additional checks on the return
  value of the `$ORDER(^%ydbAIMDERzGTIrQTVBoOhdanoKcC7(2,""),1)` (e.g. in case of a MIN function).
  If it is found to be the empty string (in case of a non-varchar-typed column) or `"#"` in case
  of a varchar-typed column, we do one more `$ORDER` to get the next non-empty (i.e. non-NULL)
  column value and return that as the aggregate function return value.

Test
----
* A new `test_aggregate_functions/TAF07` bats subtest has been added to test the optimization.

diff --git a/tests/test_aggregate_functions.bats.in b/tests/test_aggregate_functions.bats.in
--- a/tests/test_aggregate_functions.bats.in
+++ b/tests/test_aggregate_functions.bats.in
@@ -69,3 +69,23 @@ teardown() {
 	verify_output TAF06 output.txt
 }
 
+@test "TAF07 : OCTO617 : Test MAX(COL) and MIN(COL) is optimized or not in various cases where COL is a non-key-column" {
+	echo "# Run crosscheck on TAF07.sql" >> output.txt
+	run_query_in_octo_and_postgres_and_crosscheck_multiple_queries names TAF07.sql
+	echo "# Remove Octo M plans (_ydboctoP*.*) from the crosscheck run as the _ydboctoP*.m file names can differ" >> output.txt
+	echo "# when run through the JDBC driver (that uses the extended query protocol and which the crosscheck" >> output.txt
+	echo "# can invoke randomly) due to the addition of a LIMIT keyword (see YDBOcto@48c0b208 for more details)" >> output.txt
+	echo "# This can cause issues with a deterministic reference file as that includes lines from this M plan." >> output.txt
+	load_fixture customers.sql
+	load_fixture customers.zwr
+	rm _ydbocto*
+	echo "# Combine queries from TAF07.sql and TAF07_octo.sql into one query file TAF07all.sql" >> output.txt
+	cat @PROJECT_SOURCE_DIR@/tests/fixtures/TAF07.sql @PROJECT_SOURCE_DIR@/tests/fixtures/TAF07_octo.sql > TAF07all.sql
+	echo "# Run queries in TAF07all.sql using octo (for deterministic M plan names) [load_fixture TAF07all.sql]" >> output.txt
+	# Some queries can issue errors (e.g. ERR_MISTYPED_FUNCTION error when MIN(BOOLEAN) is attempted) hence the "|| true" below
+	octo -p -f TAF07all.sql >> output.txt 2>&1 || true
+	echo '# Find out which queries had M plans with $ORDER for loops. Those are the non-optimized queries.' >> output.txt
+	grep -E " select|FOR|------|ORDER|XREFDATA\(|DATA\(" $(grep -l '^;  select' _ydboctoP*.m | sort_LC_ALL_C) | grep -v %ydboctog | sed 's/.*[;:] //;' >> output.txt
+	verify_output TAF07 output.txt nodatetimefilter
+}
+
