[#679] Octo exits with non-zero code on query failure
Previously, running `octo` with a failing query via `stdin` or `-f` resulted in an exit code of `0`. This is not correct since a query failed. Accordingly, `octo` was fixed to return a non-zero exit code on query failure by adding logic to bubble up error codes to top-level (process-level) callers.

To implement this change, `run_query.c` was revised to check the return value of the callback function in the `set_STATEMENT` and `show_STATEMENT` cases and `CLEANUP_AND_RETURN` in case there was an error.  This is done so as to propagate errors from `run_query` up to the top level caller, i.e. `octo`, in all cases (other cases were previously covered by `CLEANUP_AND_RETURN`). Also, an additional `ret` variable was added to `octo.c` for retaining non-zero return codes across multiple query execution.

No tests were added, as `TUC007` already tests the `stdin` failure case (and was revised to account for new non-zero exit status) while `TSSCQ006` and `TSSCQ021` cover the `-f` case (and were similarly updated). Similarly, the pre-existing `TPC024` tests the aforementioned `set_STATEMENT`/`show_STATEMENT` error case.

However, a number of test updates were done for compatibility with these changes:
+ Fixed typo in `TPC024`: `standard_confirming_strings` -> `standard_conforming_strings`
+ Added new `run_octo_allow_error` bash function to allow tests to pass for expected errors and updated various test cases accordingly
+ Added `|| true` to load_fixture call in run_query_generator to prevent test failure for already loaded tables
+ Moved `TML` and `TUC` queries from test file to fixtures
+ Revised `build.sh` to distinguish between graceful exit of octo and asserts/SIG-11s in `test_*_upgrade` pipeline tests
+ Removed redundant fixture loading in `TQG003`

diff --git a/tests/test_helpers.bash.in b/tests/test_helpers.bash.in
--- a/tests/test_helpers.bash.in
+++ b/tests/test_helpers.bash.in
@@ -247,6 +247,16 @@ find_open_port() {
 	echo $open_port
 }
 
+run_octo_allow_error() {
+	if [[ ! -f $1 ]]; then
+		# If the input file isn't present in the current directory, it's a fixture.
+		# So, strip the comments and copy it into the working directory for use below.
+		strip_sql_comments $1
+	fi
+	# Run octo, but don't fail the test when an error is encountered. Used for testing error cases.
+	octo $3 -f $1 >> $2 2>&1 || true
+}
+
 start_rocto() {
 	create_user $USER "ydbrocks" &> /dev/null
 	echo "ROCTO START" >> env.log
diff --git a/tests/test_squirrel_sql_connect_queries.bats.in b/tests/test_squirrel_sql_connect_queries.bats.in
--- a/tests/test_squirrel_sql_connect_queries.bats.in
+++ b/tests/test_squirrel_sql_connect_queries.bats.in
@@ -1,6 +1,6 @@
 #################################################################
 #								#
-# Copyright (c) 2019-2020 YottaDB LLC and/or its subsidiaries.	#
+# Copyright (c) 2019-2021 YottaDB LLC and/or its subsidiaries.	#
 # All rights reserved.						#
 #								#
 #	This source code contains the intellectual property	#
@@ -107,11 +107,15 @@ teardown() {
   # Currently returns an error because it tries to interpret the function pg_catalog.Pg_get_keywords() as a
   # table name and ends up with an Unknown table error.
   # Also note that this query uses SQL arrays, which are currently unsupported.
+  #
+  # TODO: Further, note that the fixes for #679 cause octo to exit with a non-zero code on error,
+  # resulting in an otherwise erroneous test failure. `|| true` is added to the octo command
+  # to prevent this failure. When the above issues are resolved, this operation can be removed.
   testname="TSSCQ06"
   echo -e "\n----- ROCTO/JDBC -----" &> output.txt
   run_java run_query $test_port $testname >> output.txt 2>&1
   echo -e "\n\n----- OCTO -----" >> output.txt
-  octo -f $testname.sql >> output.txt 2>&1
+  octo -f $testname.sql >> output.txt 2>&1 || true
   # Prepend query executed
   printf '%s\n%s\n' "$(cat $testname.sql)" "$(cat output.txt)" > output.txt
   verify_output $testname output.txt noinfo
@@ -295,7 +299,8 @@ teardown() {
   echo -e "\n----- ROCTO/JDBC -----" &> output.txt
   run_java run_query $test_port $testname >> output.txt 2>&1
   echo -e "\n\n----- OCTO -----" >> output.txt
-  octo -f $testname.sql >> output.txt 2>&1
+  # Error is expected, so don't fail test with non-zero exit code by appending `|| true`
+  octo -f $testname.sql >> output.txt 2>&1 || true
   # Prepend query executed
   printf '%s\n%s\n' "$(cat $testname.sql)" "$(cat output.txt)" > output.txt
   verify_output $testname output.txt noinfo
