Optimize using cross-reference even in case both columns in WHERE clause are not keys; Print ORDER BY and JOIN TYPE in logical plan output (octo -vv OR rocto -vv)
* The main change is to src/optimization_transforms/lp_optimize_where_multi_equals_ands.c where a case
  that could have been optimized was incorrectly not optimized. An example query is the following where
  previously we would not fix the o2.customer_id key but now we do. This is now tested in
  tests/test_inner_join.bats.in.

  select o1.order_id from orders o1 inner join orders o2 on o1.customer_id = o2.customer_id;

Miscellanous changes
---------------------
* Print ORDER BY and JOIN TYPE in logical plan output (octo -vv OR rocto -vv)
* Remove unused %ydboctoi* variables from physical plan
* Expand function names in generated M code in some cases
* Fix alignment of dots in generated M code in case of lots of columns
* Add asserts after TEMPLATE_END invocations
* Fix existing test reference files now that cross reference optimization is used (and hence triggers
  are added) in more cases.

diff --git a/tests/test_helpers.bash.in b/tests/test_helpers.bash.in
--- a/tests/test_helpers.bash.in
+++ b/tests/test_helpers.bash.in
@@ -244,7 +244,7 @@ verify_output_info() {
 }
 
 count_for_loops() {
-  numloops=$(grep -c "FOR " $1 | cat)
+  numloops=$(grep -c "FOR " $1) || true	# grep -c can return non-zero status in case of no match hence the need for "|| true"
   if [[ $numloops -ne $2 ]]; then
     echo "Expected $2 FOR loops but found $numloops loops instead in $1"
     return -1
@@ -252,3 +252,11 @@ count_for_loops() {
   return
 }
 
+count_num_occurrences() {
+  numoccurrences=$(grep -c "$1" $2) || true # grep -c can return non-zero status in case of no match hence the need for "|| true"
+  if [[ $numoccurrences -ne $3 ]]; then
+    echo "Expected $3 occurrences of [$1] but found $numoccurrences occurrences instead in $2"
+    return -1
+  fi
+  return
+}
