[#892] Disable ydb_chset=UTF-8 random choice in asan-ubuntu job (avoids rare random failures)
* Over time we saw different subtests fail in the `asan-ubuntu` pipeline job with similar symptoms.
  In all cases, the failure has been a SIG-11 in the tracer (ASAN/LSAN) and the test was running in
  UTF-8 mode.

* c5a1731a and 0d2f70db addressed this issue by skipping specific subtests that have been seen to
  previously fail if the random ydb_chset choice is UTF-8 and the current job is `asan-ubuntu`.

* But we keep seeing new subtests fail in similar fashion. The latest being `TCTC013`. See
  https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/892#note_1304279789 for details.

* Therefore, this commit disables `UTF-8` as a random `ydb_chset` choice in the bats test framework
  in case the current job is `asan-ubuntu`. Only `M` is allowed in that case.

  This commit also reverts the changes in c5a1731a and 0d2f70db since those subtest-level changes are
  no longer necessary now that the disabling of `UTF-8` happens in the bats test framework.

Notes
-----
* We still see rare failures like this in-house if we link Octo with a YottaDB built using GCC + ASAN.
  But those are very rare for now (and the workaround is easy which is to use a non-GCC-ASAN build of
  YottaDB to link with Octo) so no action is taken on that front as part of this commit.

diff --git a/tests/test_helpers.bash.in b/tests/test_helpers.bash.in
--- a/tests/test_helpers.bash.in
+++ b/tests/test_helpers.bash.in
@@ -81,7 +81,17 @@ init_test() {
 	export gtmdir=$ydb_dir
 	# Randomly choose whether to use UTF-8 or M mode
 	source @YOTTADB_INCLUDE_DIRS@/ydb_env_unset
-	if [[ $(( $RANDOM % 2)) -eq 0 ]]; then
+	rand_chset=$(( $RANDOM % 2))
+	# We have seen various subtests fail occasionally with a LeakSanitizer SIG-11 when run in the "asan-ubuntu"
+	# pipeline job. All the failure runs so far have happened when ydb_chset was randomly set to "UTF-8".
+	# For lack of a better fix/workaround, we set ydb_chset to M for all subtests when run in the "asan-ubuntu" job.
+	# See https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/892#note_1156225457 and other threads in the same issue for details.
+	if [ ! -z "$CI_JOB_NAME" ] ; then
+		if [ "asan-ubuntu" == "$CI_JOB_NAME" ] ; then
+			rand_chset=1
+		fi
+	fi
+	if [[ $rand_chset -eq 0 ]]; then
 		export ydb_chset=UTF-8
 		utf8_path="/utf8"
 	else
