[#382] Fix TDTT052 to not fail because of timing issues while executing now() (and similar) queries
Issue
--------
* @nars1 noticed TDTT052 failure with the following diff
```diff
2c2
< 2024-06-05 04:56:
---
> 2024-06-05 04:57:
```
* More info about the failure can be found in https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1536#note_1937112114
* Here the minute value is differing between Octo and Postgres. This can happen when the time is close to the end of a minute
  and a query having now() (and similar date/time function) is executed using cross check function which executes the query
  one time in Octo and one time in Postgres. Small delay in execution can cause such failures.
* This issue is similar to what was fixed by https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1538

Fix
---
* Similar to https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1538, the queries with now() or similar functions
  are moved to a separate fixture
* Test queries moved have also been modified to include the entire now() (and similar) functions output. Previously seconds
  value was avoided to avoid more timing issues. Since the changes in this commit solves timing issues the cast operation
  which removed seconds value has been removed.
```
Before change
----------
select (now()::timestamp + time'01:01:01')::VARCHAR(17);

After change
----------------
select now()::timestamp + time'01:01:01';
```
* `run_query_and_crosscheck_avoiding_execution_time_delay` is added to tests/test_helpers.bash.in that executes given test
  queries in Postgres/MySql and Octo and compares the result. To avoid issues like the one described in **Issue** section
  the test queries are executed twice with Postgres/Mysql and one time with Octo. Octo result is ensured to be between the first and second
  Postgres/Mysql result if the diff command which compares first Octo result with first Postgres/Mysql result fails.
* The above function makes use of the logic implemented by https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1538 and
  enhances it to work with Postgres and MySql.
* Both TDTT052 and TDTT053 now make use of the new framework function and this fixes the issue.
* Modification to cmake/bats-tests.cmake was done to allow bash features like what is shown below.
  test_helpers.bash.in has `@VAR@` usages and this gets replaced to what `VAR` is set when configure_file is invoked in cmake.
  There are other such applications that happen when configure_file is invoked but we don't make use of it in test_helpers.bash.in.
  configure_file invocation with `@ONLY` will only substitute `@VAR@` usages and not do other substitutions.
  More details on what all gets done when configure_file gets called can be found here -> https://cmake.org/cmake/help/latest/command/configure_file.html.
  Without `@ONLY`, bash features like the one shown below couldn't be used in test_helpers.bats.in. With `@ONLY` this is now allowed
  and following command is used by the new cross check function added to get the name of the file (without extension).
  ```
  testname="${filename%.*}"
  ```

diff --git a/tests/test_helpers.bash.in b/tests/test_helpers.bash.in
--- a/tests/test_helpers.bash.in
+++ b/tests/test_helpers.bash.in
@@ -1410,3 +1410,75 @@ corecheck() {
 		ps -ef --forest >& ps_ef_forest.txt
 	fi
 }
+
+# Third argument is required to be either "postgres" or "mysql"
+run_query_and_crosscheck_avoiding_execution_time_delay() {
+	# This function is mainly for testing date/time function whose value can differ slightly depending on the time of execution.
+	# To avoid failure in such a case we take MySql/Postgres output before and
+	# after the cross check. If cross check fails the result is ensured to be between the before and after values, this
+	# confirms the validity of the result. Refer to first commit description in
+	# https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1536 for more details on what kind of failure led to this
+	# function creation.
+	db=$1
+	filename=$2
+	if [[ "postgres" = "$3" ]]; then
+		ispostgres=1
+	elif [[ "mysql" = "$3" ]]; then
+		ispostgres=0
+	else
+		exit 1
+	fi
+	testname="${filename%.*}"
+	# Fetch all select statements
+	cp @PROJECT_SOURCE_DIR@/tests/fixtures/$filename ./
+	grep "select" "$filename" >& "$testname".sql1
+	mv "$testname".sql1 "$testname".sql
+	@PROJECT_SOURCE_DIR@/tests/fixtures/sqllogic/split_queries.py  "$testname".sql
+	# Execute each query separately
+	for qfile in "$testname"-*.sql
+	do
+		qfile=${qfile%.*}
+		if [[ $ispostgres -eq 1 ]]; then
+			name="$qfile"_psql
+			# test
+			psql names -f "$qfile".sql >& "$name"_output.txt
+			octo -f "$qfile".sql >& "$qfile"_octo_output.txt
+			# post test value
+			psql names -f "$qfile".sql >& "$name"_output2.txt
+		else
+			name="$qfile"_mysql
+			# test
+			run_mysql $db "$qfile".sql >& "$name"_output.txt
+			octo --emulate=MYSQL -f "$qfile".sql >& "$qfile"_octo_output.txt
+			# post test value
+			run_mysql $db "$qfile".sql >& "$name"_output2.txt
+		fi
+		# validate result
+		verify_no_octo_or_ydb_error
+		mv "$name"_output.txt "$name"_output.log1
+		mv "$qfile"_octo_output.txt "$qfile"_octo_output.log1
+		grep ".*:.*:.*" "$name"_output.log1 >& "$name"_output.txt
+		grep ".*:.*:.*" "$qfile"_octo_output.log1 >& "$qfile"_octo_output.txt
+		if [[ $ispostgres ]]; then
+			# Remove an additional space written at the beginning
+			sed -i 's/ \(.*\)/\1/g' "$name"_output.txt
+		fi
+		diff "$name"_output.txt "$qfile"_octo_output.txt >& "$qfile".diff || true
+		if [[ -s "$qfile".diff ]]; then
+			# This can happen if the time of execution was slightly different
+			# Compare with pre-test and post-test result in this case
+			if [[ $ispostgres ]]; then
+				sed -i 's/ \(.*\)/\1/g' "$name"_output2.txt
+			fi
+			starttimestr=$(grep ".*:.*:.*" "$name"_output.txt)
+			endtimestr=$(grep ".*:.*:.*" "$name"_output2.txt)
+			nowstr=$(cat "$qfile"_octo_output.txt)
+			starttime=$(date --date="$starttimestr" +%s)
+			endtime=$(date --date="$endtimestr" +%s)
+			now=$(date --date="$nowstr" +%s)
+			echo "start time = $starttime($starttimestr), now = $now($nowstr), end time = $endtime($endtimestr)" &> "$name"_test_values.txt
+			[[ $now -le $endtime ]] && [[ $now -ge $starttime ]]
+		fi
+	done
+	return
+}
