[#502] octo.conf supports <tabletype> setting with supported values READONLY or READWRITE
* New `test_octo_conf/TOC01` bats subtest verifies valid and invalid values for `tabletype` setting.

* New `test_verbosity/TV016` bats subtest verifies the change that `verbosity` no longer accepts integer values.

* `CONFIG_ERROR_CHECK` macro had its 3rd parameter removed as it was unused.

diff --git a/tests/test_verbosity.bats.in b/tests/test_verbosity.bats.in
--- a/tests/test_verbosity.bats.in
+++ b/tests/test_verbosity.bats.in
@@ -1,6 +1,6 @@
 #################################################################
 #								#
-# Copyright (c) 2020 YottaDB LLC and/or its subsidiaries.	#
+# Copyright (c) 2020-2021 YottaDB LLC and/or its subsidiaries.	#
 # All rights reserved.						#
 #								#
 #	This source code contains the intellectual property	#
@@ -226,5 +226,12 @@ OCTO
 	grep TV015 TII06.sql > input.sql
 	octo -f input.sql -vv > output.txt 2>&1
 	verify_output TV015 output.txt
+}
+
+@test "TV016 : OCTO502 : octo disallows integers as verbosity level (only strings are accepted)" {
+	echo "verbosity = 1" > octo.conf
+	echo "# Test that [verbosity = 1] issues error" > output.txt
+	octo < /dev/null >> output.txt 2>&1 || true
+	verify_output TV016 output.txt
 }
 
