[#382] Fix TDTT053 such that second difference don't cause test failure
Issue
------
The post-merge pipeline of !1533 failed in the [make-ubuntu](https://gitlab.com/YottaDB/DBMS/YDBOcto/-/jobs/6966844482) and the [make-tls-ubuntu](https://gitlab.com/YottaDB/DBMS/YDBOcto/-/jobs/6966844493) jobs. Both failures were in the `TDTT053` subtest.

```sql
$ cat TDTT053-7.sql
select cast(localtime as time);
```

```diff
$ cat TDTT053-7.diff
1c1
< 05:08:07
---
> 05:08:08
```

The reason for the failure is that we run the `localtime` function first with `MySql` and then with `Octo`. By the time the same query runs in Octo, the time has moved on to the next second and is the cause of the diff.

This is a test issue in 41f13366 that can cause random pipeline failures.

Fix
----
* The localtime query is tested separately. Same query is executed in MySql before and after the test. If diff from the test is not empty then the output of Octo
  is verfied to be within the MySql executions results which were taken before and after the test.

Misc
----
* TDTT053 was setting `mysql_is_mariadb` but this is not required by the test so the code related to it is removed

diff --git a/tests/test_date_time_type.bats.in b/tests/test_date_time_type.bats.in
--- a/tests/test_date_time_type.bats.in
+++ b/tests/test_date_time_type.bats.in
@@ -995,14 +995,26 @@ teardown() {
 }
 
 @test "TDTT053 : OCTO382 : Test MySql emulation and date/time inbuilt functions" {
-	if [[ $(mysql --version) == *"MariaDB"* ]]; then
-		mysql_is_mariadb="true"
-	else
-		mysql_is_mariadb="false"
-	fi
-	export mysql_is_mariadb
 	run_query_in_octo_and_mysql_and_crosscheck_multiple_queries names TDTT053.sql "trim_trailing_zeroes"
-	unset mysql_is_mariadb
+	load_mysql_fixture names TDTT053localtime.sql output1.txt
+	run_query_in_octo_and_mysql_and_crosscheck_multiple_queries names TDTT053localtime.sql "trim_trailing_zeroes" || true
+	# `localtime` is being tested below. Its execution can sometimes result in seconds field having different values for
+	# Octo and MySql execution. The difference usually is 1 second. To avoid failure in such a case we take MySql output before and
+	# after the cross check function execution. If cross check fails the result is ensured to be between the two values this
+	# confirms the validiy of the result. Refer to first commit description in
+	# https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1536 for more details.
+	load_mysql_fixture names TDTT053localtime.sql output2.txt
+	if [[ -s TDTT053localtime-0.diff ]]; then
+		starttimestr=$(tail -1 output1.txt)
+		endtimestr=$(tail -1 output2.txt)
+		[[ 1 -eq $(wc -l < TDTT053localtime-0.log) ]]
+		nowstr=$(cat TDTT053localtime-0.log)
+		starttime=$(date --date=$starttimestr +%s)
+		endtime=$(date --date=$endtimestr +%s)
+		now=$(date --date=$nowstr +%s)
+		echo "start time = $starttime($starttimestr), now = $now($nowstr), end time = $endtime($endtimestr)" &> TDTT053_localtime_test_values.txt
+		[[ $now -le $endtime ]] && [[ $now -ge $starttime ]]
+	fi
 }
 
 @test "TDTT054 : OCTO382 : Test concat functions with 2 and 3 parameters" {
