Octo Query Generator - Simple Queries Changed M code and BATS test to create multiple .sql files and their proper  usage Changed M code to improve performance, limiting loop usage Added comments explaining why some sections are commented out Shortened lines Removed "query*.sql" from .gitignore Changed file names and their references to reflect change Addressed comments on MR!466

diff --git a/tests/test_helpers.bash.in b/tests/test_helpers.bash.in
--- a/tests/test_helpers.bash.in
+++ b/tests/test_helpers.bash.in
@@ -387,24 +387,35 @@ count_num_occurrences() {
 }
 
 run_query_in_octo_and_postgres_and_crosscheck() {
-    queryfile="$1"
-    file="$2"
+    database="$1"
+    queryfile="$2"
     remove="$3"
-    fname=`echo $file | sed 's/\..*//g'`
-    psql $queryfile -f $file >& $fname.psql.out
+    fname=`echo $queryfile | sed 's/\..*//g'`
+    psql $database -f $queryfile >& $fname.psql.out
     # Postgres displays boolean values as t and f whereas Octo displays them as 1 and 0 so fix that before the diff.
-    tail -n +3 $fname.psql.out | head -n -2 | sed 's/ //g;s/\<t\>/1/g;s/\<f\>/0/g;' | sort >& $fname.ref
-    octo -f $file >& $fname.octo.out
+		# Remove leading spaces, not proper ones in things like "123 fake street"
+		tail -n +3 $fname.psql.out | head -n -2 | sed 's/^[ \t]*//g;s/[ \t]*$//g;s/  //g;s/  //g;s/ | /|/g;s/ |/|/g;s/| /|/g;s/\<t\>/1/g;s/\<f\>/0/g;' | sort >& $fname.ref
+    octo -f $queryfile >& $fname.octo.out
     # Remove trailing and leading blank lines. Not yet sure why octo produces an empty line at the start for some queries
     # and an empty line at the end of the output for some other queries.
     if [[ $remove == "remove_empty_line_at_head" ]]; then
-        tail -n +2 $fname.octo.out | grep -v "^Added .*trigger" | sort >& $fname.log
+        firstline=`head -n 1 $fname.octo.out`
+        if [ "$firstline" = "" ]; then # Remove line
+          tail -n +2 $fname.octo.out | grep -v "^Added .*trigger" | sort >& $fname.log
+        else # Just create .log file
+          cat $fname.octo.out | grep -v "^Added .*trigger" | sort >& $fname.log
+        fi
         shift
     elif [[ $remove == "remove_empty_line_at_tail" ]]; then
-        head -n -1 $fname.octo.out | grep -v "^Added .*trigger" | sort >& $fname.log
+        lastline=`tail -n 1 $fname.octo.out`
+        if [ "$lastline" = "" ]; then # Remove line
+          head -n -1 $fname.octo.out | grep -v "^Added .*trigger" | sort >& $fname.log
+        else # Just create .log file
+          cat $fname.octo.out | grep -v "^Added .*trigger" | sort >& $fname.log
+        fi
         shift
     fi
-    rowcountonlycheck=$(grep -c "rowcount-only-check" $file) || true	# grep -c can return non-zero status in case of no match hence the need for "|| true"
+    rowcountonlycheck=$(grep -c "rowcount-only-check" $queryfile) || true	# grep -c can return non-zero status in case of no match hence the need for "|| true"
     if [[ $rowcountonlycheck -eq 0 ]]; then
       diff $fname.ref $fname.log >& $fname.diff
     else
