[#958] Support DEALLOCATE "STR" as a no-op (i.e. do not treat it as an error)
Background
----------
Below is pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/958

* The Rocto log shows this when using various ODBC driver applications (e.g. Excel)

  ```
  [10.0.9.4:3837] [ERROR] /tmp/octo/src/yyerror.c:363 2023-04-19 14:07:19: CUSTOM_ERROR: LINE 1:1: DEALLOCATE "_PLAN000000000AC8D780"
  [10.0.9.4:3837] [ERROR] /tmp/octo/src/yyerror.c:393 2023-04-19 14:07:19: CUSTOM_ERROR:           ^^^^^^^^^^
  [10.0.9.4:3837] [ERROR] /tmp/octo/src/yyerror.c:92 2023-04-19 14:07:19: CUSTOM_ERROR: syntax error, unexpected IDENTIFIER_ALONE
  ```

* While it's innocuous, it's desirable to just implement this as a no-op in order for this error not
  to show up in the log.

Issue
-----
* Some clients (like `isql`) that talk to rocto using the Postgres extended query wire protocol send a
  `DEALLOCATE` command with a prepared statement name once the query whose prepared statement was
  previously constructed is done executing. Since this command is unsupported in rocto, one sees the
  ERROR which can be concerning to the user.

Fix
---
* Octo needs to allow the `DEALLOCATE` command in its grammar. So looked up
  https://ronsavage.github.io/SQL/sql-92.bnf.html (which is what Octo's grammar is based on for the
  most part) and found sections that define this command and added them.

* Also looked at https://www.postgresql.org/docs/current/sql-deallocate.html and found Postgres supports
  an optional PREPARE keyword in this command that is currently ignored. So implemented the same in Octo
  as well.

* Octo now allows the `DEALLOCATE` command with an optional `PREPARE` keyword followed by a prepared
  statement name. Currently, we don't check anything about this string other than that it needs to
  be a valid `identifier` (to get through the parse phase).

* This meant introducing a new `dynamic_sql_STATEMENT` type just like we had `commit_STATEMENT`, both
  of which were unsupported. Additionally had to add a `case dynamic_sql_STATEMENT:` block to various
  existing code paths that already had a `case commit_STATEMENT:` code path (okay since both types
  are unsupported currently).

Test
----
* A new `test_odbc_connection/TOC006` subtest verifies this fix.

diff --git a/tests/test_odbc_connection.bats.in b/tests/test_odbc_connection.bats.in
--- a/tests/test_odbc_connection.bats.in
+++ b/tests/test_odbc_connection.bats.in
@@ -92,3 +92,11 @@ teardown() {
   verify_output TOC005 output.txt
 }
 
+@test "TOC006 : OCTO958 : DEALLOCATE STR needs to be supported as a no-op and not issue an error" {
+  echo "# Run a simple [select 1;] query through isql/rocto" >> output.txt
+  echo 'select 1;' | isql OCTO -b 2>&1 | tee -a output.txt
+  echo "# Check for any lines containing [ERROR] in the rocto log file. We don't expect to see any." >> output.txt
+  grep ERROR rocto.log >> output.txt || true
+  verify_output TOC006 output.txt
+}
+
